# Generated by Django 5.2.15 on 2026-06-25 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=500)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('selector_map', models.JSONField(blank=True, default=dict, help_text='CSS/XPath selectors used by the scraper for this source')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grant Source',
                'verbose_name_plural': 'Grant Sources',
                'db_table': 'grantsource',
            },
        ),
        migrations.CreateModel(
            name='ScrapedGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_title', models.TextField()),
                ('raw_html_snippet', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Structured data extracted by the scraper (title, deadline, url, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scraped_grants', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_grants', to='scrapers.grantsource')),
            ],
            options={
                'verbose_name': 'Scraped Grant',
                'verbose_name_plural': 'Scraped Grants',
                'db_table': 'scrapedgrant',
                'ordering': ['-date_scraped'],
            },
        ),
    ]
