# Generated by Django 5.2.15 on 2026-06-25 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapedgrant',
            options={'ordering': ['-scraped_at'], 'verbose_name': 'Scraped Grant', 'verbose_name_plural': 'Scraped Grants'},
        ),
        migrations.RemoveField(
            model_name='scrapedgrant',
            name='date_scraped',
        ),
        migrations.AddField(
            model_name='scrapedgrant',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, db_column='scraped_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
