# Generated by Django 5.2.15 on 2026-06-25 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_alter_scrapedgrant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedgrant',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scraped_grants', to=settings.AUTH_USER_MODEL),
        ),
    ]
