# Generated by Django 5.2.15 on 2026-06-27 12:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[accounts.models.validate_cv_file]),
        ),
    ]
