# Generated by Django 5.2.15 on 2026-06-30 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Please enter your full name (first and last) using letters only, with no numbers, dashes, or special characters.', regex='^[A-Za-z\\u0600-\\u06FF]+(?: [A-Za-z\\u0600-\\u06FF]+)+$')]),
        ),
    ]
