# Generated by Django 5.2.15 on 2026-07-11 10:20

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cover_letter', 'Cover Letter'), ('personal_statement', 'Personal Statement'), ('transcript', 'Transcript'), ('recommendation_letter', 'Recommendation Letter'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='documents/', validators=[accounts.models.validate_document_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
