# Generated by Django 5.2.15 on 2026-06-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('eligibility_text', models.TextField()),
                ('eligibility_summary', models.TextField(blank=True, help_text='AI-generated plain-language summary of eligibility.')),
                ('funding_type', models.CharField(choices=[('fully_funded', 'Fully Funded'), ('partial', 'Partial'), ('tuition_only', 'Tuition Only'), ('stipend_only', 'Stipend Only'), ('travel_grant', 'Travel Grant')], max_length=50)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant Opportunity',
                'verbose_name_plural': 'Grant Opportunities',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='GrantFieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=150)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='grants.grantopportunity')),
            ],
            options={
                'verbose_name': 'Field of Study',
                'verbose_name_plural': 'Fields of Study',
                'unique_together': {('grant', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='GrantDegreeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('diploma', 'Diploma')], max_length=20)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_levels', to='grants.grantopportunity')),
            ],
            options={
                'verbose_name': 'Degree Level',
                'verbose_name_plural': 'Degree Levels',
                'unique_together': {('grant', 'degree')},
            },
        ),
        migrations.CreateModel(
            name='GrantCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='grants.grantopportunity')),
            ],
            options={
                'verbose_name': 'Grant Country',
                'verbose_name_plural': 'Grant Countries',
                'unique_together': {('grant', 'country_name')},
            },
        ),
    ]
