# Generated by Django 5.2.15 on 2026-06-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantopportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
