# Generated by Django 5.2.15 on 2026-07-10 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grants', '0002_grantopportunity_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('explanation', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_matches', to='grants.grantopportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Match',
                'verbose_name_plural': 'AI Matches',
                'db_table': 'aimatch',
                'ordering': ['-match_score'],
            },
        ),
    ]
