<<<<<<< HEAD
# Generated by Django 5.2.15 on 2026-07-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='motivation_letter_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
=======
# Generated by Django 5.2.15 on 2026-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='motivation_letter_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
>>>>>>> e52d44f9b3615ecdc0137b648ad16168c2543723
